---
- hosts: 172.31.24.160
  become: yes
  tasks:

  - name: linux command.
    command: hostname -f
    register: myResult

  - name: Display host name.
    debug:
      msg: "{{myResult}}"

  - name: Install git software on the output of first task.
    yum:
     name: git
     state: present
    tags: mygit
    when: myResult.stderr != ""

  - name: Install tree software on the output of first task.
    yum:
     name: tree
     state: present
    tags: mygit
    when: myResult.stderr == ""

  - name: Install wget software on the output of first task. 
    yum:
     name: wget
     state: present
    tags: mywget   