---
- hosts: 172.31.22.153
  become: yes
  tasks:
  -  include_tasks: myfile.yml

  -  name: Install apache2 on webserver
     apt:
       name: apache2
       state: present
     notify: Restart server

  -  name: Change the home page text.
     template:
       src: index.j2
       dest: /var/www/html/index.html
     notify: Restart server

  handlers:
  -   name: Restart server
      service:
         name: apache2
         state: restarted