---
- hosts: all
  become: yes
  tasks:
  - name: Installing apache2 on Ubuntu Linux 18.04 node server
    apt: 
     name: apache2
     state: present
    when:  ansible_os_family == "Debian"

  - name: Installing apache2 on RedHat Linux node server
    yum: 
     name: httpd
     state: present
    when:  ansible_os_family == "RedHat"