---
- hosts: mywebservers
  become: yes
  tasks:
  - name: Installing apache2 on Ubuntu Linux 18.04 node server
    apt: 
     name: "{{mywebpackforubuntu}}"
     state: present
    when:  ansible_os_family == "Debian"

  - name: Installing apache2 on Amazon RedHat Linux and RedHat Linux node server
    yum: 
     name: "{{mywebpackforredhat}}"
     state: present
    when:  ansible_os_family == "RedHat"