---
- hosts: mywebservers
  become: yes
  tasks:
  - name: Install Java on Amazon Red Hat web servers.
    yum:
      name: "{{myjavapackforredhat}}"
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install Java on Ubuntu web servers.
    apt:
      name: "{{myjavapackforubuntu}}"
      state: present
    when: ansible_os_family == "Debian"