---
- hosts: mywebservers
  become: yes
  tasks:
  - name: Install Java on Ubuntu 18.04 web servers.
    apt:
      name: "{{myjavapackforubuntu}}"
      state: present
    when: ansible_os_family == "Debian"

  - name: Install Java on Amazon Red Hat web servers.
    apt:
      name: "{{myjavapackforredhat}}"
      state: present
    when: ansible_os_family == "RedHat"