---
- hosts: 172.31.29.183
  become: yes
  vars:
     myvar1: git
     myvar2: tree
     myvar3: wget
  tasks:
  - name: Display the value of variable
    debug: 
      msg : "{{myvar1}}"

  - name: Install softwares
    apt:
      name: "{{item}}"
      state: present
    loop: 
     - "{{myvar1}}"
     - "{{myvar2}}"
     - "{{myvar3}}"
      