---
- name:  creating the systemd service file.
  template:
    src: templates/tomcatservice.j2
    dest: /etc/systemd/system/tomcat.service

- name: reload, start, enable tomcat.
  systemd:
    name: tomcat
    daemon_reload: yes
    state: started
    enabled: yes